name: iOS Client - EAS Build (migrated to EAS)

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  push:
    branches: [main, sdk-*]
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  schedule:
    - cron: '20 5 * * *' # 5:20 AM UTC time every day

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

jobs:
  prepare:
    steps:
      - uses: eas/checkout
      - name: checkout the react-native submodule
        run: |
            echo 'pwd:'
            git submodule update --init --recursive
  build:
    name: iOS Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: ios
      profile: unversioned-client
      message: ${{ github.event.pull_request.title }}

#  send_slack_notification:
#    type: slack
#    params:
#      webhook_url: string # required
#      message: string # required if payload is not provided
#      payload: object # required if message is not provided

#  notify_failure:
#    name: 🔔 Notify on Slack
#    after: [build]
#    if: failure() && (github.event_name == 'schedule' || github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
#    type: slack
#    params:
#      webhook_url: ${{ secrets.slack_webhook_ios }}
#      message: 'Expo Go (iOS) build failed'
